---
- hosts: Linuxservers
  remote_user: ansible
  become: yes

  tasks:
  - name: Check connectivity of all the linux servers
    ping:

  - name: Installed httd packages on all the linux server
    yum:
      name: httpd
      state: latest

  - name: Start apache webservices.
    service:
      name: httpd
      state: started 
      enabled: yes

- hosts: ubuntuservers
  remote_user: ansible
  become: yes

  tasks:
  - name: Install apache2 packages on ubuntu servers
    apt:
      name: apache2
      force_apt_get: yes
      state: latest

  - name: Start apache webservices on ubuntu servers
    service: 
      name: apache2
      state: started
      enabled: yes
