---
- hosts: webservers
  remote_user: ansible-user
  become: yes
  vars:
    web_root_dir: /var/www/html
    webserver: httpd

  tasks:
   - name: "httpd package installation on webservers"
     yum:
       name: "{{ webserver }}"
       state: latest

   - name: "Start httpd service"
     service:
       enabled: true
       name: "{{ webserver }}"
       state: started

   - name: "Copying index file to webservers"
     copy:
       src: /home/ansible-user/ansible-lab/webfiles/index.html
       dest: /var/www/html
     notify:
      - restart httpd

  handlers:
   - name: restart httpd
     ansible.builtin.service:
       name: httpd
       state: restarted


---
- hosts: webservers
  remote_user: ansible-user
  become: yes
  vars:
    web_root_dir: /var/www/html
    webserver: httpd

  tasks:
   - name: "httpd package installation on webservers"
     yum:
       name: "{{ webserver }}"
       state: latest

   - name: "Start httpd service"
     service:
       enabled: true
       name: "{{ webserver }}"
       state: started

   - name: "Downlaoding Index file from GitHub"
     get_url:
       url: https://raw.githubusercontent.com/kthadikaran/ansible/master/static-website/index.html
       dest: "{{ web_root_dir }}"
     notify:
      - restart httpd

  handlers:
   - name: restart httpd
     ansible.builtin.service:
       name: httpd
       state: restarted
