
---
- hosts: webservers
  remote_user: ansible-user
  become: yes
  vars:
    web_root_dir: /var/www/html
    webserver: httpd

  tasks:
   - name: httpd package installation on webservers
     yum:
       name: "{{ webserver }}"
       state: latest

   - name: "httpd Service Up"
     service:
       enabled: true
       name: "{{ webserver }}"
       state: started

   - name: Add ports to firewalld
     firewalld:
       zone: public
       port: "{{ item }}"
       permanent: yes
       state: enabled
     when: "ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'"
     with_items:
       - 80/tcp
       - 443/tcp

   - name: Webserver Directory
     file:
       path: "{{ web_root_dir }}"

   - name: Static website deployment
     uri:
       url: https://raw.githubusercontent.com/kthadikaran/Ansible/master/static-website/index.html
