---
- hosts: all
  remote_user: ansible
  become: yes
  become_method: su  #You can also use other privilege escalation methods, like su:
  tasks:
  - name: Direcctory creation
    file:
      path: /opt/web
      state: directory
      owner: ansible
      group: ansible
      mode: 0777
  
---
- hosts: all
  remote_user: ansible
  tasks:
  - name: Direcctory creation
    file:
      path: /opt/web
      state: directory
      owner: ansible
      group: ansible
      mode: 0777
    become: yes #You can also use keyword become on a particular task instead of the whole play:
    become_method: sudo

#You can also control the order in which hosts are run. The default is to follow the order supplied by the inventory:

- hosts: all
  order: sorted
  gather_facts: False
  tasks:
 
Possible values for order are:

inventory:
    The default. The order is ‘as provided’ by the inventory
reverse_inventory:
    As the name implies, this reverses the order ‘as provided’ by the inventory
sorted:
    Hosts are alphabetically sorted by name
reverse_sorted:
    Hosts are sorted by name in reverse alphabetical order
shuffle:
    Hosts are randomly ordered each run
