---
- name: Update banner to all the servers
  hosts: all
  user: ansible
  become: true
  tasks:
       - name: Copy the banner files to remote systems
         copy: src=/home/ansible/ansible-infra/banner.txt dest=/etc/
       - name: replace banner line at sshd config
         replace:
          path: /etc/ssh/sshd_config
          regexp: '^(.*)#Banner none(.*)$'
          replace: 'Banner /etc/banner.txt'
          backup: yes
       -  name: restart the sshd service
          service:
          name: sshd
          state: restarted
