---
- hosts: ubuntulinux
  remote_user: ansible
  become: yes
  tasks:
  - name: Add multiple users on ubuntu
    user:
      name: "{{ item }}"
      groups: "sudo"
      state: present
    with_items:
      - karan
      - Jessica
      - Langton

